### ISSUE TITLE
LWJGL Library.path error

### ISSUE THREAD

**Issue by StijnSimons** [ModCoderPack/MCPBot-Issues#556]
I'm on a Mac, and compiled MCP940 (1.12) but keep getting this error when starting up:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.lwjgl.Sys$1.run(Sys.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:95)
	at org.lwjgl.Sys.<clinit>(Sys.java:112)
	at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:3266)
	at net.minecraft.client.main.Main.main(Main.java:39)
	at Start.main(Start.java:11)

(Program arguments: -Djava.library.path=versions/1.12/1.12-natives)

**Comment by StijnSimons** [comment]
Nevermind, figured it out.

**Comment by Funkey723** [comment]
I have the same issue, can you explain how you solved it?
