### ISSUE TITLE
Running issues, fixed up the ShaderManager & others.

### ISSUE THREAD

**Issue by JavasPichu** [ModCoderPack/MCPBot-Issues#856]
As far as I know, I was fixing this last night, but I believe there were errors within setting a String as a Collection<?> I believe.
However though I just set it to String in the end, if you need me to represent my code please respond.

Here's the error I receive -
[07:11:10] [Client thread/INFO]: Caught error stitching, removing all assigned resource packs
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:192) ~[guava-15.0.jar:?]
	at com.google.common.base.Joiner.toString(Joiner.java:436) ~[guava-15.0.jar:?]
	at com.google.common.base.Joiner.appendTo(Joiner.java:108) ~[guava-15.0.jar:?]
	at com.google.common.base.Joiner.appendTo(Joiner.java:152) ~[guava-15.0.jar:?]
	at com.google.common.base.Joiner.join(Joiner.java:193) ~[guava-15.0.jar:?]
	at com.google.common.base.Joiner.join(Joiner.java:183) ~[guava-15.0.jar:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.reloadResources(SimpleReloadableResourceManager.java:103) ~[bin/:?]
	at net.minecraft.client.Minecraft.refreshResources(Minecraft.java:671) [bin/:?]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:555) [bin/:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:953) [bin/:?]
	at net.minecraft.client.main.Main.main(Main.java:168) [bin/:?]
	at Start.main(Start.java:9) [bin/:?]

**Comment by simon816** [comment]
This is not related to MCP mappings. You'd be better of asking on the MinecraftForge forum https://www.minecraftforge.net/forum/ or IRC/discord
